package com.siti.ecommerce.entity;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.Data;

@Entity
@Table(name="country")
@Data
public class Country {
	
	/**
     * Attribute ID: A001
     * Key: id
     * Description: Autogenerated unique identifier for each country. Required field.
     * Constraints: Not null, Auto-generated
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false)
	private int id;
	
	/**
     * Attribute ID: A002
     * Key: code
     * Description: Country code. Required field.
     * Constraints: Not null
     */
	@Column(name = "code", nullable = false)
	private String code;
	
	/**
     * Attribute ID: A003
     * Key: name
     * Description: Country Name. Required field.
     * Constraints: Not null
     */
	@Column(name = "name", nullable = false)
	private String name;
	
	/**
     * Attribute ID: A004
     * Key: states
     * Description: List of states associated with this country. Represents the one-to-many relationship.
     * Constraints: Can be empty
     */
	@OneToMany(mappedBy="country")
	@JsonIgnore
	private List<State> states;

}
