package com.siti.ecommerce.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;

@Entity
@Table(name="state")
@Data
public class State {
	
	/**
     * Attribute ID: A001
     * Key: id
     * Description: Autogenerated unique identifier for each state. Required field.
     * Constraints: Not null, Auto-generated
     */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false)
	private int id;
	
	/**
     * Attribute ID: A002
     * Key: name
     * Description: State Name. Required field.
     * Constraints: Not null
     */
	@Column(name = "name", nullable = false)
	private String name;
	
	/**
	 * Attribute ID: A003
	 * Key: country
	 * Description: The country to which this state belongs. This field represents the many-to-one 
	 * relationship between the state and its country, indicating that each state is associated with one country.
	 * Constraints: Not null, Foreign key referencing the country entity.
	 */
	@ManyToOne
	@JoinColumn(name="country_id", nullable = false)
	private Country country;
	

}
